// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfjcsmxdezglsvhafjlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mamNzbXhkZXpnbHN2aGFmamxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODc3NjksImV4cCI6MjA3MTQ2Mzc2OX0.4Ceu9fFD15MC0mRGoKAUbOqExykwC6lAVfygwzRZCSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});